
export const DESTINATIONS: Record<string, number> = {
  'Stavanger': 2625,
  'Haugesund': 2625,
  'Bergen': 2625,
  'Ålesund': 2625,
  'Trondheim': 2625,
  'Oslo': 1575,
  'Gjøvik': 1575,
  'Drammen': 1575,
  'Arendal': 1575,
  'Kristiansand': 1575,
  'Bodø': 5250,
  'Tromsø': 5250
};

export const PRODUCT_CATEGORIES: Record<string, number> = {
  'Velg kategori...': 0,
  'Gulv/bordskjerm': 0.5,
  'Lydabsorbent vegg/tak': 0.5,
  'Pod': 2,
  'Bordlampe': 0.2,
  'Gulvlampe': 0.5,
  'Taklampe': 0.5,
  'Arbeidsbord': 0.5,
  'Elev/barnehagebord': 0.5,
  'Loungebord': 1,
  'Møte/kantinebord': 1,
  'Understell': 0.5,
  'Auditorium': 1,
  'Kjøkken': 1,
  'Låsesystem': 1,
  'Resepsjon': 1,
  'Spesialinnredning': 1,
  'Garderobeinnredning': 2,
  'Garderobeskap stål': 1,
  'Garderobeskap tre': 1,
  'Arkiv/stålhyller': 1,
  'Miljøstasjon': 1,
  'Skap/hylle': 1,
  'Elev/barnehagestol': 0.5,
  'Kontorstol': 0.5,
  'Sittegruppe': 1,
  'Stol': 0.5,
  'Gardiner m/tilbehør': 0.5,
  'Møbelstoff': 0.2,
  'Puter, pledd': 0.2,
  'Solskjerming': 0.5,
  'Tepper': 0.2,
  'Dekorativt tilbehør': 1,
  'Elektronikk, lyd, bilde': 0.5,
  'Ergonomi': 0.5,
  'Kabelhåndtering': 0.2,
  'Planter': 0.5,
  'Profileringsartikler': 1,
  'Seng og madrass': 1,
  'Skilt og merking': 1,
  'Smittevern': 0.5,
  'Tavler': 0.5,
  'Treningsutstyr': 1
};
